<?php

return [
    'SKILL_TEST_REVIEW_EXPIRED_DATE' => env('SKILL_TEST_REVIEW_EXPIRED_DATE', null),
    'APP_URL_STUDENT' => env('APP_URL_STUDENT', ''),
    'ZOOM_MANUAL_URL' => env('ZOOM_MANUAL_URL', ''),
    'APP_URL_TEACHER' => env('APP_URL_TEACHER', ''),
    'MAX_HOURS_COMMENT' => env('MAX_HOURS_COMMENT', 5),
    'AZURE_STORAGE_NAME' => env('AZURE_STORAGE_NAME', ''),
    'AZURE_STORAGE_SAS_TOKEN' => env('AZURE_STORAGE_SAS_TOKEN', ''),
    'AZURE_STORAGE_ENDPOINT' => env('AZURE_STORAGE_ENDPOINT', ''),
    'AZURE_STORAGE_URL' => env('AZURE_STORAGE_URL', ''),
    'AZURE_STORAGE_CONTAINER' => env('AZURE_STORAGE_CONTAINER', ''),
];
