INSERT INTO `send_remind_mail_pattern` VALUES (100, 22, 0, '【わたしば】コース購入完了', '#STUDENT_NAME#様\r\n\r\nこの度は、「わたしば」のご受講ありがとうございます。\r\n\r\nコース申込が完了しました。\r\nお申し込みの内容は、以下となります。\r\n\r\n------------------------------------------------------------------------\r\nコース名：#COURSE_NAME#\r\n受講回数：#COURSE_COUNT#\r\n-------------------------------------------------------------------------\r\n\r\n学習者マイページへログインしてコース内容をご確認下さい。\r\n#STUDENT_MY_PAGE_URL#\r\n\r\nなお、レッスンはzoomで実施致しますので、zoomアプリをインストールしていない方は、ご利用端末に事前にインストールしてお待ちください。\r\n#ZOOM_MANUAL_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (171, 32, 0, '【わたしば】無料登録完了', '#STUDENT_NAME#様\r\n\r\nこの度は、「わたしば」のご登録ありがとうございます。\r\nパスワードをご連絡します。\r\n\r\n------------------------------------------------------------------------\r\nパスワード：#STUDENT_PASSWORD#\r\n-------------------------------------------------------------------------\r\n\r\n学習者マイページへログインして登録内容をご確認ください。\r\n#STUDENT_MY_PAGE_URL#\r\n\r\nなお、レッスンはzoomで実施致しますので、zoomアプリをインストールしていない方は、ご利用端末に事前にインストールしてお待ちください。\r\n#ZOOM_MANUAL_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (315, 45, 0, '【わたしば】講師からコメントが届きました', '#STUDENT_NAME#様\r\n\r\nこの度は、「わたしば」のご受講ありがとうございます。\r\n#STUDENT_NAME#様がご受講されましたレッスンに講師からのコメントが届きました。\r\nご受講されたレッスンの内容は、以下となります。\r\n\r\n------------------------------------------------------------------------\r\nレッスン日：#LESSON_DATE#\r\nレッスン開始時間：#LESSON_TIME#\r\nレッスン名：#LESSON_NAME#\r\nレッスンテキスト名：#LESSON_TEXT_NAME#\r\n講師ニックネーム：#TEACHER_NICKNAME#\r\n-------------------------------------------------------------------------\r\n\r\nコメントは学習者マイページにログインしてご確認ください。\r\n#STUDENT_MY_PAGE_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (501, 3, 0, '【わたしば】無料登録完了', '#STUDENT_NAME#様\r\n\r\nこの度は、「わたしば」のご登録ありがとうございます。\r\n\r\n会員登録されますと無料体験レッスンが受講できます。\r\n学習者マイページへログインして無料体験レッスンをご予約下さい。\r\n#STUDENT_MY_PAGE_URL#\r\n\r\nなお、レッスンはzoomで実施致しますので、zoomアプリをインストールしていない方は、ご利用端末に事前にインストールしてお待ちください。\r\n#ZOOM_MANUAL_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (511, 2, 0, '【わたしば】レッスンキャンセル完了', '#STUDENT_NAME#様\r\n\r\nいつも「わたしば」をご利用いただきありがとうございます。\r\n下記レッスンのキャンセル依頼を承りました。\r\n----------------------------------------------------------------------\r\nレッスン日：#LESSON_DATE#\r\nレッスン時間：#LESSON_TIME#\r\nレッスン名：#LESSON_NAME#\r\nレッスンテキスト名：#LESSON_TEXT_NAME#\r\n講師ニックネーム:　#TEACHER_NICKNAME#\r\n----------------------------------------------------------------------\r\n\r\n#STUDENT_NAME# 様のまたのご利用を講師一同心よりお待ちしております。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (521, 6, 0, '【わたしば】パスワード変更', '#STUDENT_NAME#様\r\n\r\nいつも「わたしば」をご利用いただきありがとうございます。\r\nログインパスワードが変更されました。\r\nセキュリティのため、本メールにはパスワードを記載しません。\r\n\r\nログインID（メールアドレス）：#STUDENT_MAIL#\r\n\r\nマイページログインリンク：#STUDENT_MY_PAGE_URL#\r\n\r\nこのメール内容に心当たりのない場合は、お手数ですが破棄していただけますようお願い致します。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (531, 7, 0, '【わたしば】パスワード再発行', 'パスワードの再発行を受け付けました。\r\n下記URLにアクセスし、新しいパスワードを設定してください。\r\n\r\n#CHANGEPASS_URL#\r\n\r\nこのメール内容に心当たりのない場合は、お手数ですが破棄していただけますようお願い致します。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (541, 8, 0, '【わたしば】パスワード再発行', 'パスワードの再発行を受け付けました。\r\n下記URLにアクセスし、新しいパスワードを設定してください。\r\n\r\nパスワード再発行ページURL\r\n#CHANGEPASS_URL#\r\n\r\nこのメール内容に心当たりのない場合は、お手数ですが破棄していただけますようお願い致します。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (551, 9, 0, '【わたしば】パスワード再発行', 'パスワードの再発行を受け付けました。\r\n下記URLにアクセスし、新しいパスワードを設定してください。\r\n\r\nパスワード再発行ページURL\r\n#ADMIN_CHANGEPASS_URL#\r\n\r\nこのメール内容に心当たりのない場合は、お手数ですが破棄していただけますようお願い致します。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (581, 0, 0, '【わたしば】レッスン予約完了', '#STUDENT_NAME#様\r\n\r\nこの度は、「わたしば」のご受講ありがとうございます。\r\n下記レッスンのご予約を承りました。\r\nご予約の内容は、以下となります。今一度、ご確認ください。\r\n\r\n------------------------------------------------------------------------\r\nレッスン日：#LESSON_DATE#\r\nレッスン開始時間：#LESSON_TIME#\r\nレッスン名：#LESSON_NAME#\r\nコース名:　#COURSE_NAME#\r\nレッスンテキスト名：#LESSON_TEXT_NAME#\r\n講師ニックネーム:　#TEACHER_NICKNAME#\r\n-------------------------------------------------------------------------\r\n\r\nレッスン開始5分前になりましたら、学習者マイページにログインしてレッスンスタートボタンよりレッスンをスタートしてください。\r\n#STUDENT_MY_PAGE_URL#\r\n\r\nなお、レッスンはzoomで実施致しますので、zoomアプリをインストールしていない方は、ご利用端末に事前にインストールしてお待ちください。\r\n#ZOOM_MANUAL_URL#\r\n\r\n登録情報は、マイページの「登録情報変更」の「基本情報」より確認・変更ができます。\r\n#STUDENT_SETTING_URL#\r\n\r\n万が一、レッスン時間になっても講師より連絡がない場合は、\r\nカスタマーサービスセンターへご連絡ください。\r\n\r\nそれでは、レッスンで#STUDENT_NAME#様にお会い出来る事を楽しみにしております。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (591, 12, 0, '【わたしば】退会が完了しました', '#STUDENT_NAME#様\r\n\r\n「わたしば」をご利用いただき、ありがとうございました。\r\n「わたしば」の退会手続きが完了しました。\r\n退会時に残っていた受講回数は全て無効となりますので、ご了承くださいますようお願い申し上げます。\r\n\r\n退会手続きについて不明な点がございましたら、お手数ですが下記よりご連絡ください。\r\n\r\nお問い合わせページ：https://watashiba.jp/contact/\r\n\r\nまたのご利用を心よりお待ちしております。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (601, 1, 30, '【わたしば】レッスン開始30分前のご連絡', '#STUDENT_NAME#様\r\n\r\nこの度は、「わたしば」のご受講ありがとうございます。\r\n#STUDENT_NAME#様がご予約されましたレッスンまであと30分となりました。\r\nご予約の内容は、以下となります。今一度、ご確認ください。\r\n\r\n------------------------------------------------------------------------\r\nレッスン日：#LESSON_DATE#\r\nレッスン開始時間：#LESSON_TIME#\r\nレッスン名：#LESSON_NAME#\r\nレッスンテキスト名：#LESSON_TEXT_NAME#\r\n講師ニックネーム:　#TEACHER_NICKNAME#\r\n-------------------------------------------------------------------------\r\n\r\nレッスン開始5分前になりましたら、学習者マイページにログインしてレッスンスタートボタンよりレッスンをスタートしてください。\r\n#STUDENT_MY_PAGE_URL#\r\n\r\nなお、レッスンはzoomで実施致しますので、zoomアプリをインストールしていない方は、ご利用端末に事前にインストールしてお待ちください。\r\n#ZOOM_MANUAL_URL#\r\n\r\n登録情報は、マイページの「登録情報変更」の「基本情報」より確認・変更ができます。\r\n\r\n万が一、レッスン時間になっても講師より連絡がない場合は、\r\nカスタマーサービスセンターへご連絡ください。\r\n\r\nそれでは、レッスンで#STUDENT_NAME#様にお会い出来る事を楽しみにしております。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (611, 14, 0, '【わたしば】コース購入完了', '#STUDENT_NAME#様\r\n\r\nこの度は、「わたしば」のご受講ありがとうございます。\r\n\r\nコース購入が完了しました。\r\nご購入の内容は、以下となります。今一度、ご確認ください。\r\n\r\n------------------------------------------------------------------------\r\nコース名：#COURSE_NAME#\r\n受講回数：#COURSE_COUNT#\r\n価格：#COURSE_PRICE#\r\n支払方法：#COURSE_PAYMENT#\r\n-------------------------------------------------------------------------\r\n\r\n学習者マイページへログインしてレッスンをご予約下さい。\r\n#STUDENT_MY_PAGE_URL#\r\n\r\nなお、レッスンはzoomで実施致しますので、zoomアプリをインストールしていない方は、ご利用端末に事前にインストールしてお待ちください。\r\n#ZOOM_MANUAL_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (621, 16, 0, '【わたしば】レッスンキャンセル完了', '下記レッスンがキャンセルされました。\r\n----------------------------------------------------------------------\r\nレッスン日：#LESSON_DATE#\r\nレッスン時間：#LESSON_TIME#\r\nレッスン名：#LESSON_NAME#\r\nレッスンテキスト名：#LESSON_TEXT_NAME#\r\n講師ニックネーム:　#TEACHER_NICKNAME#\r\n----------------------------------------------------------------------\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (641, 17, 30, '【わたしば】レッスン開始30分前のご連絡', 'レッスン開始30分前になりました。\r\n\r\nレッスン開始5分前には下記URLにアクセスし準備してください。\r\n\r\n講師： #TEACHER_NAME#\r\nニックネーム： #TEACHER_NICKNAME#\r\nコース名： #COURSE_NAME#\r\nレッスン名：#LESSON_NAME#\r\nレッスン日時：#LESSON_DATE##LESSON_TIME#\r\nレッスン日時（JST）：#LESSON_DATE_JP##LESSON_TIME_JP#\r\n学習者ニックネーム:　#STUDENT_NICKNAME#　\r\nテキスト:　#LESSON_TEXT_NAME#\r\n\r\nZoomミーティングURL\r\n#ZOOM_URL#\r\n\r\n講師マイページ\r\n#TEACHER_MY_PAGE_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (651, 15, 0, '【わたしば】レッスン予約完了', '下記レッスンが予約されました。\r\n\r\nレッスン開始5分前には下記URLにアクセスし準備してください。\r\n\r\n講師： #TEACHER_NAME#\r\nニックネーム： #TEACHER_NICKNAME#\r\nコース名：#COURSE_NAME#\r\nレッスン名：#LESSON_NAME#\r\nレッスン日時：#LESSON_DATE# #LESSON_TIME#\r\nレッスン日時（JST）：#LESSON_DATE# #LESSON_TIME#\r\n学習者ニックネーム:　#STUDENT_NICKNAME#\r\nテキスト:　#LESSON_TEXT_NAME#\r\n\r\nZoomミーティングURL\r\n#ZOOM_URL#\r\n\r\n講師マイページ\r\n#TEACHER_MY_PAGE_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (661, 13, 0, '【わたしば】お問い合わせありがとうございます', '#STUDENT_NAME#様\r\n\r\nこの度は、わたしばへお問い合わせいただき誠にありがとうございます。\r\n以下、お問い合わせを承りました。\r\n\r\n------------------------------------------------------------------------\r\nお問い合わせID：#INQUIRY_ID#\r\n日時：#INQUIRY_DATE#\r\nお問い合わせ件名：#INQUIRY_TITLE#\r\nお名前：#STUDENT_NAME#\r\nメールアドレス：#STUDENT_MAIL#\r\n問い合わせ内容：#INQUIRY_BODY#\r\n-------------------------------------------------------------------------\r\n\r\nお問い合わせの返答は、上記メール宛にお送りいたします。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (664, 48, 0, '【わたしば】実力テスト評価依頼', '下記実力テストが提出されました。\r\n講師マイページにログインして、評価をお願いします。\r\n\r\n実力テストコース名：#COURSE_NAME#\r\n評価期限：#TEST_LIMIT_DATE##TEST_LIMIT_TIME#\r\n※日時は、講師ページで設定されているタイムゾーンに基づいています。\r\n\r\n講師マイページ\r\n#MY_PAGE_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (665, 49, 1440, '【わたしば】実力テスト評価依頼', '下記実力テストの評価期限まで24時間となりました。\r\n講師マイページにログインして、評価をお願いします。\r\n\r\n実力テストコース名：#COURSE_NAME#\r\n評価期限：#TEST_LIMIT_DATE##TEST_LIMIT_TIME#\r\n※日時は、講師ページで設定されているタイムゾーンに基づいています。\r\n\r\n講師マイページ\r\n#MY_PAGE_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (666, 50, 10080, '【わたしば】グループレッスン不成立のご連絡', '#STUDENT_NAME#様\r\n\r\nこの度は、「わたしば」をご利用いただき、ありがとうございます。\r\nお申し込みいただいたコースは、最小開催人数に達しなかったため、開催中止となります。\r\n\r\n------------------------------------------------------------------------\r\nコース名：#COURSE_NAME#\r\n-------------------------------------------------------------------------\r\n\r\n開催中止になったコースの代金につきましては、決済は行われません。\r\n\r\n#STUDENT_NAME#様のまたのご受講をお待ちしております。\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (667, 51, 0, '【わたしば】グループコース成立のご連絡', '#STUDENT_NAME#様\r\n\r\nこの度は、「わたしば」をご利用いただき、ありがとうございます。\r\nお申し込みいただいたコースの開催が決定しました。\r\n\r\n------------------------------------------------------------------------\r\nコース名：#COURSE_NAME#\r\n-------------------------------------------------------------------------\r\n\r\nコースの詳細スケジュールに関してはマイページにログインしご確認ください。\r\n#STUDENT_MY_PAGE_URL#\r\n\r\nこのメールは、配信専用のアドレスで配信されています。\r\nこのメールに返信されても、返信内容の確認およびご返答ができません。\r\nあらかじめご了承ください。\r\nーーーーーーーーーーーーーーーーーーーーーー\r\n【連絡先】\r\n株式会社TIJ東京日本語研修所\r\nわたしば運営事務局（https://watashiba.jp）\r\nーーーーーーーーーーーーーーーーーーーーーー');
INSERT INTO `send_remind_mail_pattern` VALUES (668, 52, 0, '【わたしば】お問合せ受付', '学習者様より新規のお問い合わせを受け付けました
------------------------------------------------------------------------
お問い合わせID：#INQUIRY_ID#
日時：#INQUIRY_DATE#
お問い合わせ件名：#INQUIRY_TITLE#
お名前：#STUDENT_NAME#
メールアドレス：#STUDENT_MAIL#
問い合わせ内容：#INQUIRY_BODY#
-------------------------------------------------------------------------');

INSERT INTO `send_remind_mail_pattern_info` VALUES (283, 501, '【WATASHIBA】Free Member Registration Completed', 'Dear #STUDENT_NAME#.\n\nThank you for registering your \"WATASHIBA\".\n\nOnce you register, you will be able to take a free trial lesson.\nPlease login to My Page to reserve your free trial lesson.\n#STUDENT_MY_PAGE_URL#\n\nThe lesson will be conducted via zoom, so if you do not have the zoom app installed, please install it on your device in advance.\n#ZOOM_MANUAL_URL#\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (285, 511, '【WATASHIBA】Lesson Cancellation Completed', 'Dear #STUDENT_NAME#.\n\nThank you for using \"WATASHIBA\".\nWe have received your cancellation request for the following lesson.\n----------------------------------------------------------------------\nLesson date: #LESSON_DATE#\nLesson time: #LESSON_TIME#\nLesson name: #LESSON_NAME#\nLesson text name: #LESSON_TEXT_NAME#\nLecturer nickname: #TEACHER_NICKNAME#\n----------------------------------------------------------------------\n\nWe look forward to hearing from #STUDENT_NAME# again soon.\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (287, 521, '【WATASHIBA】Password Change', 'Dear #STUDENT_NAME#.\n\nThank you for using \"WATASHIBA\".\nYour login password has been changed.\nFor the security, the password will not be included in this e-mail.\n\nLogin ID (e-mail address): #STUDENT_MAIL#\n\nMy Page Login Link: #STUDENT_MY_PAGE_URL#\nIf you have received this e-mail in error, please delete it.\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (289, 531, '【WATASHIBA】Password Reissue', 'Password reissue has been accepted.\nPlease access the following URL and set a new password.\n\n#CHANGEPASS_URL#\n\nIf you have received this e-mail in error, please delete it.\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (291, 541, '【WATASHIBA】 Reset password', NULL, 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (293, 551, '【WATASHIBA】　Change password', NULL, 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (299, 581, '【WATASHIBA】Lesson Reservation Completed', 'Dear #STUDENT_NAME#.\n\nThank you for taking the WATASHIBA.\nWe have received your reservation for the following lesson.\nThe details of your reservation are as follows. Please check it once again.\n\n------------------------------------------------------------------------\nLesson date: #LESSON_DATE#\nLesson start time: #LESSON_TIME#\nLesson name: #LESSON_NAME#\nCourse name: #COURSE_NAME#\nLesson text name: #LESSON_TEXT_NAME#\nLecturer nickname: #TEACHER_NICKNAME#\n-------------------------------------------------------------------------\n\nWhen it is 5 minutes before the lesson starts, please login to the My Page and click the Start Lesson button to start the lesson.\n My page login link: \n#STUDENT_MY_PAGE_URL#\n\nThe lesson will be conducted via zoom, so if you do not have the zoom app installed, please install it on your device in advance.\n#ZOOM_MANUAL_URL#\n\nYou can check and change your registration information from \"Basic Information\" in \"Change Registration Information\" on My Page.\n#STUDENT_SETTING_URL#\n\nIf you do not hear from your tutor when the lesson time comes, please contact the Customer Service Center.\n\nWe look forward to seeing #STUDENT_NAME# at the lesson.\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (301, 591, '【WATASHIBA】Withdrawal Completed.', 'Dear #STUDENT_NAME#.\n\nThank you for using our WATASHIBA.\nThe withdrawal process has been completed.\nPlease note that the remaining number of lessons will no longer be valid.\n\nIf you have any questions about the withdrawal process, please contact us from the following link.\n\nContact page: https://watashiba.jp/contact/\n\nWe are looking forward to seeing you again.\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (303, 601, '【WATASHIBA】30 Minutes Before The Lesson Starts', 'Dear #STUDENT_NAME#.\n\nThank you for taking the \"WATASHIBA\".\nThe lesson reserved by #STUDENT_NAME# is now only 30 minutes away.\nThe details of your reservation are as follows. Please check it once again.\n\n------------------------------------------------------------------------\nLesson date: #LESSON_DATE#\nLesson start time: #LESSON_TIME#\nLesson name: #LESSON_NAME#\nLesson text name: #LESSON_TEXT_NAME#\nLecturer nickname: #TEACHER_NICKNAME#\n-------------------------------------------------------------------------\n\nWhen it is 5 minutes before the lesson starts, please log in to My Page and click the Start Lesson button to start the lesson.\n#STUDENT_MY_PAGE_URL#\n\nThe lesson will be conducted via zoom, so if you do not have the zoom app installed, please install it on your device in advance.\n#ZOOM_MANUAL_URL#\n\nYou can check and change your registration information from \"\"Basic Information\"\" in \"\"Change Registration Information\"\" on My Page.\n\nIf you do not receive a call from your tutor at the time of your lesson, please contact the Customer Service Center.\n\nWe look forward to seeing #STUDENT_NAME# at your lesson.\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (305, 611, '【WATASHIBA】Course Purchase Completed', 'Dear #STUDENT_NAME#.\n\nThank you for taking the \"WATASHIBA\" course.\n\nYour course purchase has been completed.\nPlease find the purchase details below. Please check it once again.\n\n------------------------------------------------------------------------\nCourse Name: #COURSE_NAME#\nNumber of lessons: #COURSE_COUNT#\nPrice: #COURSE_PRICE#\nPayment method: #COURSE_PAYMENT#\n-------------------------------------------------------------------------\n\nPlease login to My Page to reserve a lesson.\n#STUDENT_MY_PAGE_URL#\n\nThe lesson will be conducted via zoom, so if you do not have the zoom app installed, please install it on your device in advance.\n#ZOOM_MANUAL_URL#\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (307, 621, 'レッスンキャンセル通知', NULL, 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (311, 641, 'レッスン30分前通知', NULL, 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (313, 651, 'レッスン予約通知', NULL, 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (315, 661, '【WATASHIBA】Thank You for Your Inquiry.', 'Dear #STUDENT_NAME#.\nThank you for your inquiry about our WATASHIBA.\nWe have received your inquiry, and the details are as below.\n------------------------------------------------------------------------\nInquiry ID: #INQUIRY_ID#\nDate and time: #INQUIRY_DATE#\nSubject of inquiry: #INQUIRY_TITLE#\nYour name: #STUDENT_NAME#\nE-mail address：#STUDENT_MAIL#\nInquiry contents: #INQUIRY_BODY#\n-------------------------------------------------------------------------\n\nA reply to your inquiry will be sent to the email address above.\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (317, 501, '【Học tiếng nhật trực tuyến ALC】　　Đăng ký tạm đã hoàn thành', '#STUDENT_NAME# thân mến\r\rChúng tôi xin chân thành cảm ơn bạn đã đăng ký tài khoản sử dụng hệ thống học tiếng nhật trực tuyến của chúng tôi.\r\rViệc đăng ký tài khoản tạm đã hoàn thành.\r\rXin vui lòng kích hoạt tài khoản của bạn thông qua đường dẫn dưới đây.\r#CONFIRM_URL#\r\rTrường hợp bạn không truy cập vào được đường dẫn trên, xin vui lòng copy và dán đường dẫn dưới đây lên trình duyệt và nhấn phím enter.\r<#CONFIRM_URL#>\r\rSau khi đã kích hoạt tài khoản xong, xin hãy truy cập vào đường dẫn dưới đây để xem cách sử dụng hệ thống.\rhttp://goo.gl/G0qgvV\r\rNếu có bất kỳ sự khó hiểu hoặc câu hỏi gì xin hãy vui lòng liên hệ với chúng tôi thông qua mẫu liên hệ.\r\rChúng tôi rất mong có được những bài học giữa #STUDENT_NAME# và giáo viên của chúng tôi.\r\r………………………………………………………………………………………………………\rCông ty cổ phần ALC\rBan thư ký trang học tiếng nhật trực tuyến ALC\rMẫu liên lạc ：https://nihongo-vn.alc.co.jp/user/contact\r………………………………………………………………………………………………………\r\r\r\r\r', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (319, 511, '【Học tiếng nhật trực tuyến ALC】 Huỷ bỏ đăng ký bài học đã hoàn thành', '#STUDENT_NAME# thân mến\r\rĐầu tiên chúng tôi xin chân thành cảm ơn bạn đã sử dụng hệ thống học tiếng nhật trực tuyến của chúng tôi.\r\r\rThông tin về bài học huỷ bỏ như sau:\r----------------------------------------------------------------------\rNgày học： #LESSON_DATE#\rGiờ học： #LESSON_TIME#\rTên bài học： #LESSON_NAME#\rTên tài liệu：#LESSON_TEXT_NAME#\rGiáo viên:　#TEACHER_NICKNAME#\r----------------------------------------------------------------------\r\rMong hẹn gặp lại #STUDENT_NAME# trong những bài học tới cùng với hệ thống giáo viên của chúng tôi.\r\rXin chân thành cảm ơn.\r………………………………………………………………………………………………………\rCông ty cổ phần ALC\rBan thư ký trang học tiếng nhật trực tuyến ALC\rMẫu liên lạc ：https://nihongo-vn.alc.co.jp/user/contact\r………………………………………………………………………………………………………\r', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (321, 521, '【Học tiếng nhật trực tuyến ALC】　Thông báo đã thay đổi mật khẩu', '#STUDENT_NAME# thân mến\r\rĐầu tiên chúng tôi xin chân thành cảm ơn bạn đã sử dụng hệ thống học tiếng nhật trực tuyến của chúng tôi.\r\rViệc thay đổi mật khẩu của bạn đã được hoàn thành.\r\r\rXin cảm ơn.\r………………………………………………………………………………………………………\rCông ty cổ phần ALC\rBan thư ký trang học tiếng nhật trực tuyến ALC\rMẫu liên lạc ：https://nihongo-vn.alc.co.jp/user/contact\r………………………………………………………………………………………………………\r', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (323, 531, '【Học tiếng nhật trực tuyến ALC】　Thay đổi mật khẩu', '#STUDENT_NAME# thân mến\r\rĐầu tiên chúng tôi xin chân thành cảm ơn bạn đã sử dụng hệ thống học tiếng nhật trực tuyến của chúng tôi.\r\rĐể thay đổi mật khẩu, xin hãy truy cập vào đường dẫn dưới đây:\r\r#CHANGEPASS_URL#\r\rXin chân thành cảm ơn.\r………………………………………………………………………………………………………\rCông ty cổ phần ALC\rBan thư ký trang học tiếng nhật trực tuyến ALC\rMẫu liên lạc ：https://nihongo-vn.alc.co.jp/user/contact\r………………………………………………………………………………………………………', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (325, 541, '【Học tiếng nhật trực tuyến ALC】 Thay đổi mật khẩu', 'Xin chào #TEACHER_NAME#\r\rĐể thay đổi mật khẩu, xin hãy truy cập vào đường dẫn dưới đây:\r\r#CHANGEPASS_URL#\r\rXin chân thành cảm ơn.\r\r', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (327, 551, '【アルクオンライン日本語スクール】　パスワードを変更します。', '##ADMIN_NAME# 様。\r\rこの度は、「アルクオンライン日本語スクール」のご受講ありがとうございます。\rアルクオンライン日本語スクール事務局です。\r\rパスワードの変更を下記のURLより行ってください。\r\r#CHANGEPASS_URL#\r\r変更されましたパスワードは、お忘れないようお控ください。\r\rよろしくお願いいたします。\r\r………………………………………………………………………………………………………\r株式会社アルク\rアルク オンライン日本語スクール事務局\rお問い合わせフォーム：https://nihongo-vn.alc.co.jp/user/contact\r………………………………………………………………………………………………………', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (333, 581, '【Học tiếng nhật trực tuyến ALC】 Đăng ký bài học đã hoàn thành', '#STUDENT_NAME# thân mến\r\rĐầu tiên chúng tôi xin chân thành cảm ơn bạn đã sử dụng hệ thống học tiếng nhật trực tuyến của chúng tôi.\r\r\rNội dung thông tin của bài học mà #STUDENT_NAME# đã đăng ký như sau:\r--------------------------------------------------------------\rNgày học ：#LESSON_DATE#\rGiờ học ：#LESSON_TIME#\rTên bài học：#LESSON_NAME#\rTên tài liệu：#LESSON_TEXT_NAME#\rGiáo viên:　#TEACHER_NICKNAME#\r--------------------------------------------------------------\rChúng tôi xin lưu ý rằng việc huỷ bỏ đăng ký bài phải thực hiện trước 24 tiếng đồng hồ khi bài học bắt đầu. \r\rXin chúc cho #STUDENT_NAME#  sẽ có 1 bài học thật vui vẻ và hiệu quả với hệ thống giáo viên của chúng tôi.\r\rXin chân thành cảm ơn.\r………………………………………………………………………………………………………\rCông ty cổ phần ALC\rBan thư ký trang học tiếng nhật trực tuyến ALC\rMẫu liên lạc ：https://nihongo-vn.alc.co.jp/user/contact\r………………………………………………………………………………………………………\r\r\r', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (335, 591, 'Hủy tài khoản sử dụng hệ thống Học tiếng anh trực tuyến ALC', '#STUDENT_NAME# Thân mến\r\rXin chân thành cảm ơn đã sử dụng hệ thống của chúng tôi.\r\rĐể hủy tài khoản sử dụng hệ thống, hãy tiến hành theo đường dẫn dưới đây: \r#CONFIRM_URL#\r\rXin chân thành cảm ơn.', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (337, 601, '【Học tiếng nhật trực tuyến ALC】 Thông báo còn 30 phút nữa giờ học bắt đầu', '#STUDENT_NAME# thân mến\r \rĐầu tiên chúng tôi xin chân thành cảm ơn bạn đã sử dụng hệ thống học tiếng nhật trực tuyến của chúng tôi.\r\rBài học mà #STUDENT_NAME# đã đang ký chì còn 30 phút nữa là sẽ được bắt đầu, dưới đây là thông tin về bài học săp bắt đầu, xin bạn hãy kiểm tra lại 1 lần nữa:\r\r------------------------------------------------------------------------\rNgày học：#LESSON_DATE#\rThời gian bắt đầu ：#LESSON_TIME#\rTên bài học：#LESSON_NAME#\rTên tài liệu：#LESSON_TEXT_NAME#\rGiáo viên:　#TEACHER_NICKNAME#\r-------------------------------------------------------------------------\r\rTrước khi bắt đầu học 5 phút, xin bạn hãy vui lòng đăng nhập sẵn vào skype và đợi cuộc gọi từ giáo viên của chúng tôi.\rNào và bay giờ xin chúc #STUDENT_NAME# sẽ có 1 bài học thật vui vẻ và hiệu quả với giáo viên của chúng tôi.\r\rXin chân thành cảm ơn.\r………………………………………………………………………………………………………\rCông ty cổ phần ALC\rBan thư ký trang học tiếng nhật trực tuyến ALC\rMẫu liên lạc ：https://nihongo-vn.alc.co.jp/user/contact\r………………………………………………………………………………………………………', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (339, 611, '【Học tiếng nhật trực tuyến ALC】　Mua khóa học đã hoàn thành', '#STUDENT_NAME# thân mến\r\rĐầu tiên chúng tôi xin chân thành cảm ơn bạn đã sử dụng hệ thống học tiếng nhật trực tuyến và mua khóa học của chúng tôi.\r\rThông tin về khóa học mà #STUDENT_NAME#  đã mua như sau:\r\r--------------------------------------------------------------\r\rMã số đặt hàng：#ORDER_ID#\r\rMã số khoá học ：#COURSE_ID#\r\rTên khoá học ：#COURSE_NAME#\r\rLệ phí khóa học ：#COURSE_PRICE#　円\r\r(Thuế)：#COURSE_TAX#　円\r\rTổng tiền thanh toán：#COURSE_TOTAL#　円\r\rNgày giờ thanh toán：#ORDER_DATE#\r\rThời hạn sử dụng khoá học：#EXPIRE_DATE#\r\r\rXin chân thành cảm ơn.\r………………………………………………………………………………………………………\rCông ty cổ phần ALC\rBan thư ký trang học tiếng nhật trực tuyến ALC\rMẫu liên lạc ：https://nihongo-vn.alc.co.jp/user/contact\r………………………………………………………………………………………………………', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (341, 621, 'レッスンキャンセル通知', ' #TEACHER_NAME# 先生\r\r以下のレッスンがキャンセルされました。\r\r----------------------------------------------------------------------\r\rレッスン日：#LESSON_DATE#\r\rレッスン時間：#LESSON_TIME#\r\rレッスン名：#LESSON_NAME#\r\rテキスト名 ：#LESSON_TEXT_NAME#\r\r----------------------------------------------------------------------\r\rこのメールは自動送信メールです。\r（このメールに返信しないでください）\r\r\rTeacher\'s Page URL\rhttps://nihongo-system.alc.co.jp/tutor.swf\r', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (345, 641, 'レッスン30分前通知', ' #TEACHER_NAME# 先生\r\r下記レッスンまで30分となりました。\r生徒名:　#STUDENT_NICKNAME#\rレッスン日:　#LESSON_DATE#\rレッスン時間:　#LESSON_TIME#\rレッスン名:　#LESSON_NAME#\rテキスト名:　#LESSON_TEXT_NAME#\r\rこのメールは自動送信メールです。\r（このメールに返信しないでください）\r\r\rTeacher\'s Page URL\rhttps://nihongo-system.alc.co.jp/tutor.swf\r', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (347, 651, 'レッスン予約通知', ' #TEACHER_NAME# 先生\r\rあなたのレッスンが予約されました。\r\r生徒名:　#STUDENT_NICKNAME#\r\rレッスン日:　#LESSON_DATE#\rレッスン時間:　#LESSON_TIME#\rレッスン名:　#LESSON_NAME#\rテキスト名:　#LESSON_TEXT_NAME#\r\rこのメールは自動送信メール。\r（このメールに返信しないでください）\r\r\rTeacher\'s Page URL\rhttps://nihongo-system.alc.co.jp/tutor.swf\r\r\r', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (349, 661, '【アルクオンライン日本語スクール】　新しいお問い合わせが来ました', '#ADMIN_NAME#様\r\r\r\r新しいお問い合わせがありました。\r\rお問い合わせの内容は、以下となります。\r\r\r\r------------------------------------------------------------------------\r\rお問い合わせID：#INQUIRY_ID#\r\r日時：#INQUIRY_DATE#\r\rお問い合わせ件名：#INQUIRY_TITLE#\r\rお名前：#USER_TITLE#\r\rメールアドレス：#USER_EMAIL#\r\r問い合わせ内容：#INQUIRY_BODY#\r\r-------------------------------------------------------------------------\r\r\r\rアルクオンライン日本語スクール事務局\r\r……………………………………………………………………\r\r株式会社アルク　\r\rアルクオンライン日本語スクール事務局\r\rjpn_info@alc.co.jp\r\r……………………………………………………………………', 'vn');
INSERT INTO `send_remind_mail_pattern_info` VALUES (350, 315, '【WATASHIBA】Comments from the lecturers has been received', 'Dear #STUDENT_NAME#.\n\nThank you for taking the lesson, WATASHIBA.\nWe have received comments from the lecturer for the lesson taken by #STUDENT_NAME#.\nThe lesson details are as follows.\n\n------------------------------------------------------------------------\nLesson date: #LESSON_DATE#\nLesson start time: #LESSON_TIME#\nLesson name: #LESSON_NAME#\nLesson text name: #LESSON_TEXT_NAME#\nLecturer nickname: #TEACHER_NICKNAME#\n-------------------------------------------------------------------------\n\nPlease login to My Page to see the comments.\n#STUDENT_MY_PAGE_URL#\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (353, 100, '【WATASHIBA】Course Purchase Completed', 'Dear #STUDENT_NAME#.\n\nThank you for taking the \"WATASHIBA\" course.\n\nYour course application has been completed.\nPlease find below the details of your application.\n\n------------------------------------------------------------------------\nCourse name: #COURSE_NAME#\nNumber of lessons: #COURSE_COUNT#\n-------------------------------------------------------------------------\n\nPlease login to My Page to check your course details.\n#STUDENT_MY_PAGE_URL#\n\nIf you do not have the zoom app installed, please install it on your device in advance. \n#ZOOM_MANUAL_URL#\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (356, 171, '【WATASHIBA】Free Registration Completed', 'Dear #STUDENT_NAME#.\n\nThank you for registering your \"WATASHIBA\".\nWe will send you a Password.\n\n------------------------------------------------------------------------\nPassword: #STUDENT_PASSWORD#\n-------------------------------------------------------------------------\n\nPlease login to My Page to check your registration details.\n#STUDENT_MY_PAGE_URL#\n\nThe lesson will be conducted via zoom, so if you do not have the zoom app installed, please install it on your device in advance.\n#ZOOM_MANUAL_URL#\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (363, 664, '【服務名稱】實力測試評估請求', '提交了下述能力測試。\n\n請登錄講師我的頁麵要求進行評估。\n\n能力測試課程：#COURSE_NAME#\n評估期限（JST）：#TEST_LIMIT_DATE##TEST_LIMIT_TIME#\n\n講師主頁\n#MY_PAGE_URL#\n\n※此郵件是從一個隻發送的電子郵件地址發出的。\n   所以，無法回複您的電子郵件。\n……………………………………………………………………………………………\n連絡先\n\n……………………………………………………………………………………………', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (364, 665, '【服務名稱】實力測試評估請求', '現在還剩下24小時來評估以下能力測試。\r\n請登錄講師我的頁麵要求進行評估。\r\n\r\n能力測試課程名稱：#COURSE_NAME#\r\n評價期限（JST）：#TEST_LIMIT_DATE##TEST_LIMIT_TIME#\r\n\r\n講師主頁\r\nマイページ URL\r\n※此郵件是從一個隻發送的電子郵件地址發出的。\r\n   所以，無法回複您的電子郵件。\r\n…………………………………………………………………………………\r\n連絡先\r\n\r\n…………………………………………………………………………………', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (365, 666, '【WATASHIBA】Notification of Voided Group Lesson', 'Dear #STUDENT_NAME#.\nThank you for using \"WATASHIBA\".\nWe are very sorry to inform you that the course you signed up for will not be held as it did not reach the minimum number of participants.\n\n------------------------------------------------------------------------\nCourse Name: #COURSE_NAME#\n-------------------------------------------------------------------------\n\nNo lesson fee will be charged for the aforementioned course.\n\nWe look forward to seeing #STUDENT_NAME# in near future.\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (366, 666, '【わたしば】小组課程取消通知', '#STUDENT_NAME#學員\n\n感謝您使用“わたしば”。\n您申請的課程因未達到開課標準的人數而中止舉辦。 \n------------------------------------------------------------------------\n學科課程名稱：#COURSE_NAME#\n-------------------------------------------------------------------------\n\n取消課程的費用將不予支付。\n\n#STUDENT_NAME# 歡迎您再次參加。\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (367, 667, '【WATASHIBA】Notice of Group Course Approval', 'Dear #STUDENT_NAME#.\n\nThank you for your interest in WATASHIBA.\nWe are pleased to inform you that the course you have applied for has been approved.\n\n------------------------------------------------------------------------\nCourse name: #COURSE_NAME#\n------------------------------------------------------------------------\n\nPlease log in to My Page to confirm the detailed schedule of the course.\n#STUDENT_MY_PAGE_URL#\n\nThis email has been sent from a send-only address. \nPlease note that we are unable to check or reply to you even if you reply to this e-mail.\nーーーーーーーーーーーーーーーーーーーーーー\n【Contact】\nTIJ Tokyo Institute of Japanese\nWatashiba Management Office（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'en');
INSERT INTO `send_remind_mail_pattern_info` VALUES (368, 667, '【WATASHIBA】團體開課通知', '#STUDENT_NAME#\n\n感謝您使用“WATASHIBA”。\n申请的课程已经决定開課。\n\n------------------------------------------------------------------------\n課程名稱：#COURSE_NAME#\n------------------------------------------------------------------------\n\n請登錄我的頁面查看課程的詳細時間表。\n#STUDENT_MY_PAGE_URL#\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (369, 591, '【わたしば】提現已完成', '#STUDENT_NAME#學員\n\n感謝您聽講“WATASHIBA”。\n“WATASHIBA”已完整退出程序。\n \n退出時剩餘的聽課次數全部無效，敬請諒解。\n\n關於退會手續如果有不明白的地方的話，麻煩您從下麵的聯係方式聯係。\n\n聯係人頁麵: https://watashiba.jp/contact/\n\n衷心期待您的再次光臨。\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (370, 531, '【服務名稱】重發密碼', '已接受重新發布密碼的聯係。 \n請訪問下麵的URL並設置新密碼。 \n\n#CHANGEPASS_URL#\n\n如果你不認可這封郵件的內容、請刪除它。\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (371, 521, '在“更改注冊信息”屏幕中更改密碼的學員', '#STUDENT_NAME#學員\n\n感謝您一直使用“服務名稱”。 \n您的登錄密碼已更改。 \n為了安全起見，本郵件不包含密碼。 \n\n登錄ID（電子郵件地址）：#STUDENT_MAIL#\n\n#STUDENT_MY_PAGE_URL#\n\n如果你不認可這封郵件的內容、請刪除它。\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (372, 501, '[WATASHIBA 免費注冊完成', '#STUDENT_NAME#學員\n\n感謝您注冊“WATASHIBA”。\n\n注冊會員後可以參加免費體驗課程。 \n請登錄學員個人頁麵預約免費體驗課程。 \n#STUDENT_MY_PAGE_URL#\n\n此外，課程將在zoom上進行，因此如果您沒有安裝zoom應用程序，\n請在您的終端上安裝zoom應用程序並等待。\n#ZOOM_MANUAL_URL#\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (373, 611, '【服務名稱】課程購買完成', '#STUDENT_NAME#學員\n\n這次，感謝您聽講“服務名稱”。 \n\n課程購買完成。 \n購買的內容如下。 請再確認一次。\n------------------------------------------------------------------------\n學科課程名稱：#COURSE_NAME#\n聽課次數：#COURSE_COUNT#\n價格：#COURSE_PRICE#\n付款方式：#COURSE_PAYMENT#\n-------------------------------------------------------------------------\n請登錄學員個人頁麵預約課程。\n#STUDENT_MY_PAGE_URL#\n\n此外，課程將在zoom上進行，因此如果您沒有安裝zoom應用程序，\n請在您的終端上安裝zoom應用程序並等待。\n#ZOOM_MANUAL_URL#\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (374, 171, '[服務名稱] 免費注冊完成', '#STUDENT_NAME#學員\n\n感謝您注冊“服務名稱”。\n聯係密碼\n------------------------------------------------------------------------\n密碼：#STUDENT_PASSWORD#\n-------------------------------------------------------------------------\n\n請登錄學員 \"\"我的主頁\"\"，查看您的注冊信息。\n#STUDENT_MY_PAGE_URL#\n\n此外，課程將在zoom上進行，因此如果您沒有安裝zoom應用程序，\n請在您的終端上安裝zoom應用程序並等待。\n#ZOOM_MANUAL_URL#\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (375, 100, '【服務名稱】課程購買完成', '#STUDENT_NAME#學員\n\n這次，感謝您聽講“服務名稱”。 \n\n課程申請完成。 \n申請的內容如下。 \n------------------------------------------------------------------------\n學科課程名稱：#COURSE_NAME#\n上課次數：#COURSE_COUNT#\n-------------------------------------------------------------------------\n\n請登錄學員我的主頁查看課程內容。\n#STUDENT_MY_PAGE_URL#\n\n此外，課程將在zoom上進行，因此如果您沒有安裝zoom應用程序，\n請在您的終端上安裝zoom應用程序並等待。\n#ZOOM_MANUAL_URL#\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (376, 601, '【服務名稱】開課30分前聯係', '#STUDENT_NAME#學員\n\n感謝您使用“服務名稱”。\n#STUDENT_NAME#  學員，30 分鍾後開始預約的課程。\n預約的詳細內容如下。 請再次確認。\n------------------------------------------------------------------------\n開課日：#LESSON_DATE#\n開課日期：#LESSON_TIME#\n課程名稱：#LESSON_NAME#\n使用教材：#LESSON_TEXT_NAME#\n講師昵稱:　#TEACHER_NICKNAME#\n-------------------------------------------------------------------------\n在課程開始5分鍾前，請登錄“學員自己的頁麵”並使用“課程開始”按鈕開始課程。\n#STUDENT_MY_PAGE_URL#\n\n此外，課程將在zoom上進行，因此如果您沒有安裝zoom應用程序，請在您的終端上安裝zoom應用程序並等待。\n#ZOOM_MANUAL_URL#\n\n注冊信息時，可以在自己頁麵的“注冊信息變更”裏的“基本信息”中確認和變更。 \n\n如果已到了上課時間可還沒有老師在線， \n請與客戶服務中心聯係。 \n\n那麽，等待在課程中與#STUDENT_NAME#學員見麵。\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (377, 581, '[服務名稱] 課程預約完成', '#STUDENT_NAME#學院\n\n這次，感謝您聽講“服務名稱”。 \n接受了下述課程的預約。 \n預約的內容如下。 請再確認一次。 \n------------------------------------------------------------------------\n上課日：#LESSON_DATE#\n上課時間：#LESSON_TIME#\n課程名稱：#LESSON_NAME#\n課程教材：#LESSON_TEXT_NAME#\n講師昵稱:　#TEACHER_NICKNAME#\n-------------------------------------------------------------------------\n在課程開始前5分鍾，請登錄“學員我的頁麵”並使用“課程開始”按鈕開始課程。\n#STUDENT_MY_PAGE_URL#\n\n此外，課程將在zoom上進行，因此如果您沒有安裝zoom應用程序，請在您的終端上安裝zoom應用程序並等待。\n#ZOOM_MANUAL_URL#\n\n注冊信息時，可以在我的主頁的“注冊信息變更”裏的“基本信息”中確認和變更。 \n\n如果已到了上課時間可還沒有老師在線， \n請與客戶服務中心聯係。 \n\n那麽，等待在課程中與#STUDENT_NAME#學員見麵。\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (378, 511, '[服務名稱] 課程取消完成', '#STUDENT_NAME#學員\n\n感謝您一直使用“服務名稱”。 \n收到了取消下述課程的請求。\n----------------------------------------------------------------------\n上課日：#LESSON_DATE#\n上課時間：#LESSON_TIME#\n課程名稱：#LESSON_NAME#\n課程教材：#LESSON_TEXT_NAME#\n講師昵稱:　#TEACHER_NICKNAME#\n----------------------------------------------------------------------\n\n#STUDENT_NAME# 全體講師衷心等待您的再次使用。\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (379, 661, '【服务名称】谢谢您的查询', '#STUDENT_NAME#學員\n\n感謝您聯係服務名稱。\n我們已收到以下詢問。\n------------------------------------------------------------------------\n查詢ID：#INQUIRY_ID#\n日期：#INQUIRY_DATE#\n查詢主題：#INQUIRY_TITLE#\n姓名：#STUDENT_NAME#\n電子郵件地址：#STUDENT_MAIL#\n查詢內容：#INQUIRY_BODY#\n-------------------------------------------------------------------------\n查詢內容的答複將發送到上述郵件地址\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');
INSERT INTO `send_remind_mail_pattern_info` VALUES (380, 315, '【わたしば】講師發來點評信息', '#STUDENT_NAME#學員\n\n這次，感謝您聽講“わたしば”。\n#STUDENT_NAME# 所學課程的講師已發表評論。\n所學內容如下。\n\n------------------------------------------------------------------------\n上課日：#LESSON_DATE#\n課程開始時間：#LESSON_TIME#\n課程名稱：#LESSON_NAME#\n課文名稱：#LESSON_TEXT_NAME#\n代課講師昵稱:　#TEACHER_NICKNAME#\n-------------------------------------------------------------------------\n\n請登錄 \"學員我的主頁 \"查看評論。\n#STUDENT_MY_PAGE_URL#\n\n此電子郵件將發送到僅發送地址。\n即使您回复此電子郵件，您也無法確認或回复該回复。\n親實現諒解。\nーーーーーーーーーーーーーーーーーーーーーー\n【聯繫地址】\n株式会社TIJ東京日本語研修所\n我是管理處（https://watashiba.jp）\nーーーーーーーーーーーーーーーーーーーーーー', 'zh');

INSERT INTO `send_remind_mail_timing` VALUES (0, 'レッスン予約後（学習者用）');
INSERT INTO `send_remind_mail_timing` VALUES (1, 'レッスン開始前（学習者用）');
INSERT INTO `send_remind_mail_timing` VALUES (2, 'レッスンキャンセル後（学習者用）');
INSERT INTO `send_remind_mail_timing` VALUES (3, '一般会員　無料登録後');
INSERT INTO `send_remind_mail_timing` VALUES (6, '学習者用パスワード変更後');
INSERT INTO `send_remind_mail_timing` VALUES (7, '学習者用パスワードを忘れた場合');
INSERT INTO `send_remind_mail_timing` VALUES (8, '講師用パスワードを忘れた場合');
INSERT INTO `send_remind_mail_timing` VALUES (9, '管理者用パスワードを忘れた場合');
INSERT INTO `send_remind_mail_timing` VALUES (12, '退会学習者に返信');
INSERT INTO `send_remind_mail_timing` VALUES (13, 'ユーザー問い合わせ時');
INSERT INTO `send_remind_mail_timing` VALUES (14, '一般会員　コース購入完了');
INSERT INTO `send_remind_mail_timing` VALUES (15, 'レッスン予約後（講師用）');
INSERT INTO `send_remind_mail_timing` VALUES (16, 'レッスンキャンセル後（講師用）');
INSERT INTO `send_remind_mail_timing` VALUES (17, 'レッスン開始前（講師用）');
INSERT INTO `send_remind_mail_timing` VALUES (22, '一括登録　法人会員　コース申込');
INSERT INTO `send_remind_mail_timing` VALUES (32, '一括登録　法人会員　新規登録');
INSERT INTO `send_remind_mail_timing` VALUES (45, '講師コメント登録時メール');
INSERT INTO `send_remind_mail_timing` VALUES (48, '実力テスト評価依頼');
INSERT INTO `send_remind_mail_timing` VALUES (49, '実力テスト評価リマインド');
INSERT INTO `send_remind_mail_timing` VALUES (50, 'グループレッスン人数未到達');
INSERT INTO `send_remind_mail_timing` VALUES (51, 'グループレッスン人数到達');
INSERT INTO `send_remind_mail_timing` VALUES (52, 'お問合せ受付');
